print (zip('abc', 'xyz'))
print (list(zip('abc', 'xyz')))
print ('==================')
R = range(10)
print (R)
print (list(range(10)))
print ('==================')

M = map(abs, (-1, 0, 1))
for x in M: print(x)
print (list(map(abs, (-1, 0, 1))))
print ('==================')

Z = zip((1, 2, 3), (10, 20, 30))
for pair in Z: print(pair)
print ('==================')

D = dict(a=1, b=2, c=3)
print (D)
for k in D.keys(): print(k, end=' ')
print ('\n==================')
V = D.values()
for (k, v) in D.items(): print(k, v, end=' ')
print ('\n==================')
print (D)
for k in sorted(D.keys()): print(k, D[k], end=' ')
print ('\n==================')
for k in sorted(D): print(k, D[k], end=' ')
