D = {'a':1, 'b':2, 'c':3}
print (D.keys() & D.keys())
print (D.keys() & {'b'})
print (D.keys() & {'b': 1})
print (D.keys() | {'b', 'c', 'd'})
print ('============')
D = {'a': 1}
print (list(D.items()))
print (D.items() | D.keys())
print (D.items() | D)
print (D.items() | {('c', 3), ('d', 4)})
print (dict(D.items() | {('c', 3), ('d', 4)}))
print ('============')
D = {'a':1, 'b':2, 'c':3}
print (D)
Ks = D.keys()
Ks = list(Ks)
Ks.sort()
for k in Ks: print(k, D[k])
print (D)
Ks = D.keys()
for k in sorted(Ks): print(k, D[k])
for k in sorted(D): print(k, D[k])
print ('============')
print (D)
if 'c' in D: print('present', D['c'])
print(D.get('c'))
print(D.get('x'))
if D.get('c') != None: print('present', D['c'])
